// <auto-generated />
using Fiap.Api.GestaoDeResiduos.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Fiap.Api.GestaoDeResiduos.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.AterroModel", b =>
                {
                    b.Property<int>("IdAterro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmLocalizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QqtdAtual")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QtdAterro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<bool>("StCapacidade")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdAterro");

                    b.ToTable("Aterro", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.CaminhaoModel", b =>
                {
                    b.Property<int>("IdCaminhao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCaminhao"));

                    b.Property<string>("NmLocalizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QtdAtual")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("VlCapacidade")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdCaminhao");

                    b.ToTable("Caminhao", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.ColetaModel", b =>
                {
                    b.Property<int>("IdColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColeta"));

                    b.Property<int>("IdCaminhao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmLocalizacao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("StColeta")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdColeta");

                    b.HasIndex("IdCaminhao");

                    b.ToTable("Coleta", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.FuncionarioModel", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"));

                    b.Property<int>("IdCaminhao")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmDept")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmFuncao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmFuncionario")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("IdCaminhao");

                    b.ToTable("Funcionario", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.RotaModel", b =>
                {
                    b.Property<int>("IdRota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRota"));

                    b.Property<int>("IdAterro")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdCaminhao")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("IdRota");

                    b.HasIndex("IdCaminhao")
                        .IsUnique();

                    b.ToTable("Rota", (string)null);
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.AterroModel", b =>
                {
                    b.HasOne("Fiap.Api.GestaoDeResiduos.Model.RotaModel", "Rota")
                        .WithOne("Aterro")
                        .HasForeignKey("Fiap.Api.GestaoDeResiduos.Model.AterroModel", "IdAterro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rota");
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.ColetaModel", b =>
                {
                    b.HasOne("Fiap.Api.GestaoDeResiduos.Model.CaminhaoModel", "Caminhao")
                        .WithMany("Coletas")
                        .HasForeignKey("IdCaminhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.FuncionarioModel", b =>
                {
                    b.HasOne("Fiap.Api.GestaoDeResiduos.Model.CaminhaoModel", "Caminhao")
                        .WithMany("Funcionarios")
                        .HasForeignKey("IdCaminhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.RotaModel", b =>
                {
                    b.HasOne("Fiap.Api.GestaoDeResiduos.Model.CaminhaoModel", "Caminhao")
                        .WithOne("Rota")
                        .HasForeignKey("Fiap.Api.GestaoDeResiduos.Model.RotaModel", "IdCaminhao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caminhao");
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.CaminhaoModel", b =>
                {
                    b.Navigation("Coletas");

                    b.Navigation("Funcionarios");

                    b.Navigation("Rota")
                        .IsRequired();
                });

            modelBuilder.Entity("Fiap.Api.GestaoDeResiduos.Model.RotaModel", b =>
                {
                    b.Navigation("Aterro");
                });
#pragma warning restore 612, 618
        }
    }
}
